import type { Metadata } from "next";
import { Abel } from "next/font/google";
// import "../../app/components/";
import  Header  from "../components/header";


const abel = Abel({
  subsets: ["latin"],
  weight: '400',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={abel.className}>

        <Header />
        {children}
      </body>
    </html>
  );
}
