import type { Metadata } from "next";
import { Abel } from "next/font/google";
import "./globals.css";
import  Header  from "./components/header";


const inter = Abel({
  subsets: ["latin"],
  weight: '400',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>


        {children}
      </body>
    </html>
  );
}
